# Generated by Django 4.1.3 on 2023-03-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="tag", name="content_type",),
        migrations.RemoveField(model_name="tag", name="object_id",),
    ]
