# Generated by Django 4.1.3 on 2023-01-04 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farmacia", "0002_farmacia_author"),
    ]

    operations = [
        migrations.RenameModel(old_name="Farmacia", new_name="Remedios",),
    ]
