# Generated by Django 4.1.3 on 2023-01-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0003_rename_farmacia_remedios"),
    ]

    operations = [
        migrations.RemoveField(model_name="remedios", name="preparation_time",),
        migrations.RemoveField(model_name="remedios", name="preparation_time_unit",),
        migrations.RemoveField(model_name="remedios", name="servings",),
        migrations.RemoveField(model_name="remedios", name="servings_unit",),
        migrations.AddField(
            model_name="remedios", name="price", field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="remedios",
            name="cover",
            field=models.ImageField(
                blank=True, default="", upload_to="farmacia/covers/%Y/%m/%d/"
            ),
        ),
    ]
