# Generated by Django 4.1.3 on 2023-01-07 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0004_remove_remedios_preparation_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remedios",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="farmacia.category",
            ),
        ),
        migrations.AlterField(
            model_name="remedios",
            name="cover",
            field=models.ImageField(
                blank=True,
                default="farmacia/static/images/default.jpg",
                upload_to="farmacia/covers/%Y/%m/%d/",
            ),
        ),
    ]
