# Generated by Django 4.1.3 on 2023-01-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0005_alter_remedios_category_alter_remedios_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remedios",
            name="cover",
            field=models.ImageField(
                blank=True,
                default="images/default.jpg",
                upload_to="farmacia/covers/%Y/%m/%d/",
            ),
        ),
    ]
