# Generated by Django 4.1.3 on 2023-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0008_alter_remedios_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="remedios",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
