# Generated by Django 4.1.3 on 2023-02-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0009_remedios_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remedios", name="description", field=models.TextField(),
        ),
    ]
