# Generated by Django 4.1.3 on 2023-03-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_remove_tag_content_type_remove_tag_object_id"),
        ("farmacia", "0012_alter_remedios_options_alter_remedios_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="remedios",
            name="preparetion_steps",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="remedios",
            name="tags",
            field=models.ManyToManyField(null=True, to="tags.tag", verbose_name="TAG"),
        ),
    ]
