# Generated by Django 4.1.3 on 2023-03-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_remove_tag_content_type_remove_tag_object_id"),
        ("farmacia", "0013_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remedios",
            name="preparetion_steps",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="remedios",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tags.tag", verbose_name="TAG"),
        ),
    ]
